export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INSUFFICIENT_CREDITS: 'INSUFFICIENT_CREDITS',
  PAYMENT_REQUIRED: 'PAYMENT_REQUIRED',
  MODERATION_BLOCKED: 'MODERATION_BLOCKED',
  ACCOUNT_BANNED: 'ACCOUNT_BANNED',
  EMAIL_UNVERIFIED: 'EMAIL_UNVERIFIED',
  MAINTENANCE: 'MAINTENANCE',
  INTERNAL: 'INTERNAL',
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;

export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
  VALIDATION_ERROR: 422,
  UNAUTHORIZED: 401,
  INVALID_TOKEN: 401,
  TOKEN_EXPIRED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  RATE_LIMITED: 429,
  INSUFFICIENT_CREDITS: 402,
  PAYMENT_REQUIRED: 402,
  MODERATION_BLOCKED: 422,
  ACCOUNT_BANNED: 403,
  EMAIL_UNVERIFIED: 403,
  MAINTENANCE: 503,
  INTERNAL: 500,
};

export interface ApiErrorEnvelope {
  error: {
    code: ErrorCode;
    message: string;
    details?: unknown;
    request_id: string;
  };
}
