/**
 * Machine-readable error codes, their HTTP status mapping, and the single error
 * envelope shape returned by every endpoint. Imported by the server error
 * handler and the client apiClient so both sides speak the same language.
 */

export const ERROR_CODES = {
  // 400
  BAD_REQUEST: 'BAD_REQUEST',
  // 401
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  // 402
  INSUFFICIENT_CREDITS: 'INSUFFICIENT_CREDITS',
  PAYMENT_REQUIRED: 'PAYMENT_REQUIRED',
  // 403
  FORBIDDEN: 'FORBIDDEN',
  ACCOUNT_BANNED: 'ACCOUNT_BANNED',
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',
  // 404
  NOT_FOUND: 'NOT_FOUND',
  // 409
  CONFLICT: 'CONFLICT',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  ILLEGAL_TRANSITION: 'ILLEGAL_TRANSITION',
  // 422
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  MODERATION_BLOCKED: 'MODERATION_BLOCKED',
  UNKNOWN_EVENT: 'UNKNOWN_EVENT',
  // 429
  RATE_LIMITED: 'RATE_LIMITED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  // 500 / 503
  INTERNAL: 'INTERNAL',
  MAINTENANCE: 'MAINTENANCE',
  SERVER_RESTART: 'SERVER_RESTART',
  STREAM_FAILED: 'STREAM_FAILED',
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;

export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  TOKEN_EXPIRED: 401,
  INVALID_TOKEN: 401,
  INVALID_CREDENTIALS: 401,
  EMAIL_NOT_VERIFIED: 401,
  INSUFFICIENT_CREDITS: 402,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  ACCOUNT_BANNED: 403,
  ACCOUNT_DELETED: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  EMAIL_TAKEN: 409,
  ILLEGAL_TRANSITION: 409,
  VALIDATION_ERROR: 422,
  MODERATION_BLOCKED: 422,
  UNKNOWN_EVENT: 422,
  RATE_LIMITED: 429,
  ACCOUNT_LOCKED: 429,
  INTERNAL: 500,
  MAINTENANCE: 503,
  SERVER_RESTART: 503,
  STREAM_FAILED: 500,
};

export interface ApiErrorEnvelope {
  error: {
    code: ErrorCode;
    message: string;
    details?: unknown;
    request_id: string;
  };
}

export function httpStatusFor(code: ErrorCode): number {
  return ERROR_HTTP_STATUS[code];
}
